name: Lint

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: First linting step - Black
        uses: psf/black@stable

      - name: Second linting step - Ruff 
        uses: astral-sh/ruff-action@v1