name: Mypy Type Check

on: 
    pull_request:
    push:
      branches:
        - main

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install -r requirements.txt

      - name: Install mypy types
        run: |
          mypy --install-types

      - name: Run mypy
        run: |
          mypy --config-file mypy.ini .
