name: Mypy Type Check

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  type-check: # job name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync --frozen
        # installs from pyproject.toml + uv.lock

      - name: Run mypy
        run: uv run mypy --install-types --non-interactive .
